### ISSUE TITLE
Rename type to message_type in schemas

### ISSUE THREAD

**Issue by nbuffon** [Orange-OpenSource/its-client#207] opened 2024-11-14 10:31 UTC
All SDK have to align on using this new field name

**Comment by ymorin-orange** [comment] 2024-11-21 10:53
* `type` -> `message_type`
* `origin` -> `delete`
* order of fields in schema for ease of comparison : fields common to all messages at the top, others below
* neighbourhood, region: add `source_uuid`, `timestamp`, and `validity_duration`
* status: `cellular` and `gnss` are not required.
* srem, ssem: move to sub-directories

**Comment by ymorin-orange** [comment] 2024-11-21 11:00
Duplicate of #137

**Closed by ymorin-orange** 2024-11-21 11:00 UTC
Labels: Rust, Python, Java, Schema
